<?php

/**
 * @file
 * Subtypes allow more specificity without having to create dedicated entity types.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function schemadotorg_additional_type_help(string $route_name, RouteMatchInterface $route_match): string|NULL {
  if ($route_name === 'schemadotorg_additional_type.settings') {
    return '<p>' . t('The <strong>Schema.org additional type settings</strong> page allows administrators to configure default setting for additional typing.') . '<p>';
  }

  return NULL;
}

/* ************************************************************************** */
// Schema.org mapping defaults.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_mapping_defaults_alter().
 */
function schemadotorg_additional_type_schemadotorg_mapping_defaults_alter(array &$defaults, string $entity_type_id, ?string $bundle, string $schema_type): void {
  /** @var \Drupal\schemadotorg_additional_type\SchemaDotOrgAdditionalTypeManagerInterface $additional_type_manager */
  $additional_type_manager = \Drupal::service('schemadotorg_additional_type.manager');
  $additional_type_manager->mappingDefaultsAlter($defaults, $entity_type_id, $bundle, $schema_type);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function schemadotorg_additional_type_form_schemadotorg_mapping_form_alter(array &$form, FormStateInterface &$form_state): void {
  /** @var \Drupal\schemadotorg_additional_type\SchemaDotOrgAdditionalTypeManagerInterface $additional_type_manager */
  $additional_type_manager = \Drupal::service('schemadotorg_additional_type.manager');
  $additional_type_manager->alterMappingForm($form, $form_state);
}

/* ************************************************************************** */
// Node add/edit form enhancements.
/* ************************************************************************** */

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function schemadotorg_additional_type_node_prepare_form(NodeInterface $node, string $operation, FormStateInterface $form_state): void {
  /** @var \Drupal\schemadotorg_additional_type\SchemaDotOrgAdditionalTypeManagerInterface $additional_type_manager */
  $additional_type_manager = \Drupal::service('schemadotorg_additional_type.manager');
  $additional_type_manager->nodePrepareForm($node, $operation, $form_state);
}

/**
 * Implements hook_link_alter().
 */
function schemadotorg_additional_type_link_alter(array &$variables): void {
  /** @var \Drupal\Core\Url|null $url */
  $url = $variables['url'] ?? NULL;
  if (!$url
    || !$url->isRouted()
    || $url->getRouteName() !== 'node.add'
    || !empty($url->getOption('query'))) {
    return;
  }

  /** @var \Drupal\schemadotorg_additional_type\SchemaDotOrgAdditionalTypeManagerInterface $additional_type_manager */
  $additional_type_manager = \Drupal::service('schemadotorg_additional_type.manager');
  $additional_type_manager->linkAlter($variables);
}

/* ************************************************************************** */
// Schema.org JSON-LD.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 *
 * Besides, altering an existing Schema.org mapping's JSON-LD data, modules can
 * define custom JSON-LD data for any entity type.
 */
function schemadotorg_additional_type_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity): void {
  // Check that the additional type property is set and is string, if not exit.
  if (empty($data['additionalType']) || !is_string($data['additionalType'])) {
    return;
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');

  /** @var \Drupal\schemadotorg\SchemaDotOrgNamesInterface $schema_name */
  $schema_name = \Drupal::service('schemadotorg.names');

  // If the additional type property is valid subtype move it to the @type
  // and unset the additionalType property.
  $additional_type = $data['additionalType'];
  $additional_type = str_replace(' ', '_', $additional_type);
  $additional_type = $schema_name->snakeCaseToUpperCamelCase($additional_type);
  if ($schema_type_manager->isSubTypeOf($additional_type, $data['@type'])) {
    $data['@type'] = $additional_type;
    unset($data['additionalType']);
  }
}

/* ************************************************************************** */
// Schema.org types settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_additional_type_form_schemadotorg_types_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_additional_type'] = [
    '#type' => 'details',
    '#title' => t('Additional type settings'),
  ];
  $form['schemadotorg_additional_type']['default_types'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Default additional types'),
    '#description' => t('Enter Schema.org types that support additional typing by default.'),
    '#description_link' => 'types',
    '#example' => '
- SchemaType
- bundle
',
  ];
  $form['schemadotorg_additional_type']['required_types'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Required additional types'),
    '#description' => t('Enter Schema.org types and bundles whose additional type field should be required.'),
    '#description_link' => 'types',
    '#example' => '
- SchemaType
- entity_type_id--SchemaType
- bundle
',
  ];
  $form['schemadotorg_additional_type']['default_allowed_values'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org default additional types allowed values'),
    '#description' => t('Enter default additional type allowed values for Schema.org types.')
      . ' '
      . t('Additional type allowed values that are not valid Schema.org types will be rendered as an <a href=":href">additionalType</a> property via JSON-LD', [':href' => 'https://schema.org/additionalType'])
      . ' '
      . t('Additional type values can be snake case machine names that will automatically be converted to Schema.org types when appropriate.'),
    '#description_link' => 'types',
    '#example' => '
SchemaType:
  schema_subtype_01: Subtype 01
  schema_subtype_02: Subtype 02
  schema_subtype_03: Subtype 03
SchemaType--bundle:
  schema_subtype_01: Subtype 01
  schema_subtype_02: Subtype 02
  schema_subtype_03: Subtype 03
entity_type_id--bundle:
  schema_subtype_01: Subtype 01
  schema_subtype_02: Subtype 02
  schema_subtype_03: Subtype 03
bundle:
  schema_subtype_01: Subtype 01
  schema_subtype_02: Subtype 02
  schema_subtype_03: Subtype 03
',
  ];
  $form['schemadotorg_additional_type']['use_snake_case'] = [
    '#type' => 'checkbox',
    '#title' => t('Use snake case for additional type values'),
    '#description' => t('If checked, additional type value will automatically be snake cased.'),
    '#return_value' => TRUE,
  ];
}
