schemadotorg_options.settings:
  type: config_object
  label: 'Schema.org Options settings'
  mapping:
    schema_property_allowed_values:
      type: sequence
      label: 'Schema.org property'
      sequence:
        type: sequence
        label: 'Allowed values'
        sequence:
          type: text
          label: Text
    schema_property_allowed_values_remove:
      type: sequence
      label: 'Schema.org property allowed values remove prefixes/suffixes'
      sequence:
        type: text
        label: 'Schema.org property allowed values remove prefix/suffix'
    allowed_value_text:
      type: sequence
      label: 'Allowed value text'
      sequence:
        type: string
        label: 'Allowed values text'
    allowed_value_uris:
      type: sequence
      label: 'Allowed value URIs'
      sequence:
        type: uri
        label: 'Allowed values URI'
