schemadotorg_type_tray.settings:
  type: config_object
  label: 'Schema.org Type tray settings'
  mapping:
    existing_nodes_link_text:
      type: string
      label: 'Text to be used when building links to existing content'
