schemadotorg_epp.settings:
  type: config_object
  label: 'Schema.org Entity prepopulate settings'
  mapping:
    node_links:
      type: sequence
      label: 'Node Links'
      sequence:
        type: sequence
        label: 'Schema.org types'
        sequence:
          type: string
          label: 'Schema.org type node link'
    node_links_display:
      type: string
      label: 'Node links display'
