<?php

/**
 * @file
 * Integrates the Entity Reference Override field.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_entity_reference_override_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  /** @var \Drupal\schemadotorg_entity_reference_override\SchemaDotOrgEntityReferenceOverrideManagerInterface $entity_reference_override_manager */
  $entity_reference_override_manager = \Drupal::service('schemadotorg_entity_reference_override.manager');
  $entity_reference_override_manager->propertyFieldAlter(
    $schema_type,
    $schema_property,
    $field_storage_values,
    $field_values,
    $widget_id,
    $widget_settings,
    $formatter_id,
    $formatter_settings
  );
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function schemadotorg_entity_reference_override_field_widget_single_element_entity_reference_override_autocomplete_form_alter(array &$element, FormStateInterface $form_state, array $context): void {
  /** @var \Drupal\schemadotorg_entity_reference_override\SchemaDotOrgEntityReferenceOverrideManagerInterface $entity_reference_override_manager */
  $entity_reference_override_manager = \Drupal::service('schemadotorg_entity_reference_override.manager');
  $entity_reference_override_manager->singleElementEntityReferenceOverrideFormAlter($element, $form_state, $context);
}

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_entity_reference_override_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  /** @var \Drupal\schemadotorg_entity_reference_override\SchemaDotOrgEntityReferenceOverrideManagerInterface $entity_reference_override_manager */
  $entity_reference_override_manager = \Drupal::service('schemadotorg_entity_reference_override.manager');
  $entity_reference_override_manager->jsonLdSchemaPropertyAlter($value, $item, $bubbleable_metadata);
}

/* ************************************************************************** */
// Schema.org properties settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_entity_reference_override_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_entity_reference_override'] = [
    '#type' => 'details',
    '#title' => t('Entity reference override settings'),
  ];
  $form['schemadotorg_entity_reference_override']['schema_properties'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Entity reference overrides alteration'),
    '#description' => t('Enter the Schema.org properties that should use the Entity Reference Override field to support <a href=":href">https://schema.org/Role</a>.', [':href' => 'https://schema.org/Role']),
    '#description_link' => 'properties',
    '#example' => "
member:
  placeholder: 'Enter member role'
employee:
  placeholder: 'Enter employee role'
MedicalStudy--member:
  type: select
  size: null
  required: true
  options:
    '': '- None -'
    'Principle Investigator': 'Principle Investigator'
    'Co-Investigator': 'Co-Investigator'
",
  ];

}
