schemadotorg_auto_entitylabel.settings:
  type: config_object
  label: 'Schema.org Inline Entity Form settings'
  mapping:
    default_types:
      type: sequence
      label: 'Default types'
      sequence:
        type: mapping
        label: 'Default types'
        mapping:
          pattern:
            type: string
            label: 'Pattern for the label'
          escape:
            type: boolean
            label: 'Remove special characters'
          preserve_titles:
            type: boolean
            label: 'Preserve node titles'
