<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Drupal hooks for supporting Mermaid Diagram field.
 */

/**
 * Implements hook_theme().
 */
function mermaid_diagram_field_theme() {
  return [
    'mermaid_diagram_field' => [
      'render element' => 'elements',
    ],
    'mermaid_diagram' => [
      'template' => 'mermaid_diagram',
      'variables' => [
        'preface' => '',
        'title' => t('Diagram'),
        'mermaid' => '',
        'caption' => '',
        'key' => '',
        'show_code' => '',
        'postface' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function mermaid_diagram_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mermaid_diagram_field':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
