schemadotorg_inline_entity_form.settings:
  type: config_object
  label: 'Schema.org Inline entity form settings'
  mapping:
    default_schema_properties:
      type: sequence
      label: 'Schema.org default properties'
      sequence:
        type: string
        label: 'Schema.org default property'
    default_type_form_displays:
      type: sequence
      label: 'Default type form displays'
      sequence:
        type: string
        label: 'Default type form display'
    default_form_display_components:
      type: sequence
      label: 'Default form display components'
      sequence:
        type: string
        label: 'Default form display component'
